### PR TITLE
renamed to MailPipes fixes #26

### LINKED ISSUE #26: Rename email_transactional to mail_pipes
Make sure there are no dependencies that could break.

We made that decision here: #24

### PR DESCRIPTION
**Pull request by zduci**

### CODE REVIEW

**Comment by luxerama** [comment]
@zduci i actually preferred mail pipes more, one less char to type.

**Comment by zduci** [comment]
haha cool, i'll change it

**Comment by zduci** [comment]
@luxerama all yours

**Comment by luxerama** [comment]
@zduci do you think we should keep the transactional logic in a transactional namespace?

**Comment by zduci** [comment]
@luxerama :ok_hand:

**Pull request merged**
