### PR TITLE
Feature/store emails

### PR DESCRIPTION
**Pull request by zduci**

### CODE REVIEW

**Comment by luxerama** [comment]
@zduci waiting for https://codeclimate.com/github/thebeansgroup/email_transactional to be fixed

**Comment by luxerama** [comment]
sorry I mean https://codeclimate.com/github/thebeansgroup/email_transactional/compare/feature/store-emails

**Comment by zduci** [comment]
@luxerama :ok_hand:

**Comment by zduci** [comment]
@luxerama 
screen shot 2016-01-28 at 11 11 19

**Pull request closed without merging**
